# Generated by Django 5.1.1 on 2024-09-15 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("plugin_name", models.CharField(max_length=100, unique=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("permission_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="DataUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("db_name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("table_name", models.CharField(max_length=255)),
                ("source_name", models.CharField(max_length=255)),
                (
                    "data_upload",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="plugins.dataupload"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("db_file", models.CharField(max_length=255)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("edition_datetime", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("user", "db_file")},
            },
        ),
    ]
